### PR TITLE
#28: wrap baza fetch network failures in typed Error

### PR DESCRIPTION
**Pull request by VasilevNStas**
Problem:
`baza()` calls `fetch()` without error handling for network-level failures. When DNS resolution, TCP connection, or TLS handshake fails, a raw `TypeError("fetch failed")` propagates instead of the consistent `Error` type that callers expect.

Solution:
Wrap the `fetch()` call in try/catch and re-throw as `Error` with a descriptive message prefix:
- `Network failure for {method} {uri}: {message}`
- The existing HTTP status error handling (non-200 responses) is unchanged
- A regression test uses `jest.spyOn` to mock a `fetch` rejection and asserts the wrapped `Error` type and message

Checklist:
- [x] `npx eslint .` — 0 errors
- [x] `npx jest --config jest.config.ts --no-color --ci test/baza.test.ts -t 'wraps network'` — passed
- [x] `npx tsc --target es2020 --module nodenext --outDir dist src/baza.ts src/to_gpt.ts` — passed

Notes:
- Full `npx jest --config jest.config.ts --no-color --ci` has pre-existing failures in test/baza.test.ts and test/server.test.ts that require a real ZEROCRACY_TOKEN; the new focused regression passes in isolation
- The `Error.cause` option was intentionally omitted to stay compatible with the project's `--target es2020` TypeScript compilation

### CODE REVIEW

**Comment by VasilevNStas** [comment]
@yegor256 @edmoffo please review

**Review by kreinba — APPROVED** [review]
Try/catch wraps the fetch rejection in a fresh Error with the method, URI, and underlying message, jest and eslint pass locally, the existing HTTP-status path is untouched. Addresses #28; another open pull request resolves the same issue, so only one can be merged. 0 inline comments.

**Comment by VasilevNStas** [comment]
@yegor256 @edmoffo please re-review

**Comment by yegor256** [comment]
@VasilevNStas see: https://www.yegor256.com/2025/04/19/dont-merge-into-broken-master.html

**Comment by VasilevNStas** [comment]
@yegor256 I've fixed the TypeScript compilation errors in prompts.ts and tools.ts (TS2589 + implicit any types) that were causing the make/test CI failure.

The remaining two CI failures (checkmake and eslint) are **pre-existing infrastructure issues** in the repository, not related to this PR:
- **checkmake**: Makefile lint rules (missing `clean` in .PHONY, `it` target body too long) — fixed in PR #64
- **eslint**: `@eslint/js` version conflict with eslint@9 — fixed in PR #64

Once #64 is merged, this PR should pass all checks after a rebase.

**Comment by yegor256** [comment]
@VasilevNStas conflicts here

**Comment by yegor256** [comment]
Please fix the merge conflicts so this pull request can be merged.

**Review by kreinba — APPROVED** [review]
The try/catch around fetch wraps network-level rejections in a typed Error with method, URI, and underlying message, matching the contract issue #28 requires. The existing HTTP-status branch is untouched. The regression test mocks fetch to reject and asserts both the Error type and the prefix. CI is green and the targeted jest run passes locally. The Error.cause omission is acceptable given the es2020 compile target the author called out.

**Comment by 0crat** [comment]
@vasilevnstas Thanks for the contribution! You've earned +20 points for this: +24 as a basis; -4 for too few (24) hits-of-code. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running score is [+2258](https://zerocracy.github.io/judges-action/zerocracy-vitals.html); don't forget to check your [Zerocracy account](https://www.zerocracy.com/) too).
